parameters:
  # Optional: dependencies of the job
  dependsOn: ''

  artifactsDir: $(Build.StagingDirectory)/artifacts

  gitHubUser: dotnet-build-bot
  gitHubEmail: dotnet-build-bot@microsoft.com
  gitHubAuthToken: $(AccessToken-dotnet-build-bot-public-repo)

  versionsRepoOwner: dotnet
  versionsRepo: versions

jobs:
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 1440 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          clrdiagd@microsoft.com
        instructions: 'Please validate the DAC assets and resume'
  
  - template: /eng/common/templates/job/publish-build-assets.yml
    parameters:
      configuration: Release
      pool:
        name: NetCore1ESPool-Svc-Internal
        demands: ImageOverride -equals Build.Windows.10.Amd64.VS2017
      dependsOn:
      - waitForValidation
      - ${{ if ne(parameters.dependsOn,'') }}:
        - ${{ parameters.dependsOn }}
      publishUsingPipelines: true
